config/routes.rb
Rails.application.routes.draw do
  resources :magazines
  resources :oenologists
  devise_for :users
  resources :strains
  resources :wines
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'wines#index'
  authenticated do
    root to: "wines#index", as: :authenticated_root
  end
end

app/models/wine.rb
class Wine < ApplicationRecord
    has_many :wine_oenologists, dependent: :destroy
    has_many :oenologists, through: :wine_oenologists, dependent: :destroy
    has_many :wine_strains, inverse_of: :wine, class_name:'WineStrains'
    has_many :strains, inverse_of: :wine, class_name:'Strain', through: :wine_strains, dependent: :destroy
    accepts_nested_attributes_for :wine_strains, allow_destroy: true
    accepts_nested_attributes_for :strains, allow_destroy: true
    accepts_nested_attributes_for :wine_oenologists, allow_destroy: true
    accepts_nested_attributes_for :oenologists, allow_destroy: true
    validates :name, presence: true
    validates_associated :wine_strains
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
  before_action :authenticate_user!
  before_action :authorize_editor!, only: %i[ new create edit update destroy ]
  before_action :set_wine, only: %i[ show edit update destroy ]

  # GET /wines or /wines.json
  def index
    @wines = Wine.all
    @wine_strains = WineStrains.where(wine_id: :id)
  end

  # GET /wines/1 or /wines/1.json
  def show
  end

  # GET /wines/new
  def new
    @wine = Wine.new
    @wine.wine_strains.build
    @oenologists = Oenologist.all.order(:name)
  end

  # GET /wines/1/edit
  def edit
    @strains = Strain.all.order(:name)
    @oenologists = Oenologist.all.order(:name)
  end

  # POST /wines or /wines.json
  def create
    @wine = Wine.new(wine_params)

    respond_to do |format|
      if @wine.save
        format.html { redirect_to @wine, notice: "Wine was successfully created." }
        format.json { render :show, status: :created, location: @wine }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wines/1 or /wines/1.json
  def update
    respond_to do |format|
      if @wine.update(wine_params)
        format.html { redirect_to @wine, notice: "Wine was successfully updated." }
        format.json { render :show, status: :ok, location: @wine }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @wine.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wines/1 or /wines/1.json
  def destroy
    @wine.destroy
    respond_to do |format|
      format.html { redirect_to wines_url, notice: "Wine was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wine
      @wine = Wine.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def wine_params
      params.require(:wine).permit(:name, :year, :grade, {oenologist_ids: []}, wine_strains_attributes: [:id, :wine_id, :strain_id, :percentage, :_destroy])
    end
end

app/helpers/wines_helper.rb
module WinesHelper
    def strains_for_select
        Strain.order(:name).collect { |g| [g.name, g.id] }
    end
end

app/views/wines/_form.html.erb
<%= form_with(model: wine, local: true) do |form| %>
  <% if wine.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wine.errors.count, "error") %> prohibited this wine from being saved:</h2>

      <ul>
      <% wine.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.number_field :year %>
  </div>

  <div id="wine_strains" class="form-group">
    <%= form.fields_for :wine_strains do |wine_strains_form| %>
    <%= render 'wine_strain_fields', f: wine_strains_form %>
    <% end %>
    <div class="links form-inline">
      <%= link_to_add_association 'add strain', form, :wine_strains %>
    </div>
  </div>

  <div class="field">
    <%= form.label :grade %> 
    <%= form.number_field :grade, step: :any %>
  </div>

  <div class="field">
    <%= form.label :oenologists %>
      <%= form.collection_check_boxes(:oenologist_ids, Oenologist.all, :id, :name) do |b| %>
        <%= b.label class:"label-checkbox" do%>
          <%= b.check_box + b.text %>
        <% end %>
      <% end %>
  </div>

  <br>

  <div class="actions">
    <%= form.submit %>
  </div>

  <%= link_to 'New Strain', new_strain_path %>
  
<% end %>

app/views/wines/_wine_strain_fields.html.erb
<div class="nested-fields form-inline">
    <%= f.select :strain_id, strains_for_select, {}, class: 'custom-select mx-sm-3 mb-2' %>
    <div class="form-group mr-sm-3 mb-2">
        <%= f.label :percentage, '%' %>
        <%= f.text_field :percentage, class: 'form-control mr-sm-3' %>
    </div>
</div>

app/views/wines/edit.html.erb
<h1>Editing Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Show', @wine %> |
<%= link_to 'Back', wines_path %>

app/views/wines/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wines</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Year</th>
      <th>Strains</th>
      <th>Grades</th>
      <th>Oenologist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wines.each do |wine| %>
      <tr>
        <td><%= wine.name %></td>
        <td><%= wine.year %></td>
        <td>
          <% wine.wine_strains.order_by_strain_name.each do |wine_strain| %>
            <li style="list-style-type: none";><%= wine_strain.strain.name %><%= " (#{wine_strain.percentage}%)" %></li>
          <% end %>
        </td>
        <td><%= wine.grade %></td>
        <td>
          <% WineOenologist.where(wine_id: wine.id).each do |wine_oenologist| %>
            <li><%= wine_oenologist.oenologist.name %></li>
          <% end %>
        </td>
        <td><%= link_to 'Show', wine %></td>
        <td><%= link_to 'Edit', edit_wine_path(wine) %></td>
        <td><%= link_to 'Destroy', wine, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wine', new_wine_path %>
<%= link_to 'New Strain', new_strain_path %>
<%= link_to 'New Oenologist', new_oenologist_path %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form', wine: @wine %>

<%= link_to 'Back', wines_path %>

app/views/wines/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @wine.name %>
</p>

<p>
  <strong>Year:</strong>
  <%= @wine.year %>
</p>

<%= link_to 'Edit', edit_wine_path(@wine) %> |
<%= link_to 'Back', wines_path %>